<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Social Network Highload - Documentation" />
    <title>Social Network Highload - Documentation</title>
    <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@4.5.0/swagger-ui.css" />
</head>

<body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@4.5.0/swagger-ui-bundle.js" crossorigin></script>
    <script>
        window.onload = () => {
            window.ui = SwaggerUIBundle({
                url: window.location.origin + "/docs/docs.json",
                dom_id: "#swagger-ui",
                persistAuthorization: true,
                displayOperationId: true,
                filter: true,
                plugins: [
        SwaggerUIBundle.plugins.DownloadUrl,
        function() {
            return {
                statePlugins: {
                    spec: {
                        wrapActions: {
                            updateJsonSpec: function(oriAction, system) {
                                return (spec) => {
                                    spec.servers = [{url: window.location.origin + "/api/"}]
                                                return oriAction(spec)
                                            }
                                        }
                                    }
                    }
                }
            }
                    }
    ],
            });
};
</script>
</body>

</html>